#!/usr/bin/env bash
# iidm-viewer installer.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/gautierbureau/iidm-viewer/main/install.sh | bash
#
# What it does:
#   1. Verifies python3 >= 3.9 (and python3-venv) is available.
#   2. Creates ~/.iidm_viewer/ with a dedicated virtualenv.
#   3. pip-installs iidm-viewer from PyPI into that venv.
#   4. Writes ~/.iidm_viewer/launch.sh, a wrapper that reuses an
#      already-running server instead of spawning duplicates.
#   5. Adds an `iidm-viewer` alias to ~/.bashrc.
#   6. Installs an Ubuntu .desktop entry + icon so the app shows up
#      in the applications menu.

set -euo pipefail

INSTALL_DIR="$HOME/.iidm_viewer"
VENV_DIR="$INSTALL_DIR/venv"
LAUNCHER="$INSTALL_DIR/launch.sh"
ICON_FILE="$INSTALL_DIR/iidm-viewer.svg"
DESKTOP_DIR="$HOME/.local/share/applications"
DESKTOP_FILE="$DESKTOP_DIR/iidm-viewer.desktop"
PORT=8501
MIN_PY_MAJOR=3
MIN_PY_MINOR=9

log()  { printf '\033[1;34m[iidm-viewer]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[iidm-viewer]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[iidm-viewer]\033[0m %s\n' "$*" >&2; exit 1; }

# -----------------------------------------------------------------------------
# 1. Python prerequisites
# -----------------------------------------------------------------------------
PYTHON_BIN="$(command -v python3 || true)"
[[ -n "$PYTHON_BIN" ]] || die "python3 not found. Install Python >= ${MIN_PY_MAJOR}.${MIN_PY_MINOR} first."

PY_VER="$("$PYTHON_BIN" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")')"
"$PYTHON_BIN" - <<PYEOF || die "Python ${PY_VER} found but >= ${MIN_PY_MAJOR}.${MIN_PY_MINOR} is required."
import sys
sys.exit(0 if sys.version_info >= (${MIN_PY_MAJOR}, ${MIN_PY_MINOR}) else 1)
PYEOF
log "Using $PYTHON_BIN (Python $PY_VER)"

if ! "$PYTHON_BIN" -c 'import venv' 2>/dev/null; then
    die "The 'venv' module is missing. On Debian/Ubuntu run: sudo apt install python3-venv"
fi

# -----------------------------------------------------------------------------
# 2. Virtualenv + package install
# -----------------------------------------------------------------------------
mkdir -p "$INSTALL_DIR"

if [[ ! -x "$VENV_DIR/bin/python" ]]; then
    log "Creating virtualenv in $VENV_DIR"
    "$PYTHON_BIN" -m venv "$VENV_DIR"
else
    log "Reusing existing virtualenv in $VENV_DIR"
fi

log "Upgrading pip"
"$VENV_DIR/bin/pip" install --quiet --upgrade pip

log "Installing iidm-viewer from PyPI (this can take a few minutes)"
"$VENV_DIR/bin/pip" install --upgrade iidm-viewer

# -----------------------------------------------------------------------------
# 3. Launcher (reuses an already-running server on port $PORT)
# -----------------------------------------------------------------------------
log "Writing launcher to $LAUNCHER"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Auto-generated by the iidm-viewer installer. Do not edit by hand;
# re-run install.sh to regenerate.
set -euo pipefail

INSTALL_DIR="$INSTALL_DIR"
VENV_DIR="\$INSTALL_DIR/venv"
PORT=$PORT
URL="http://localhost:\$PORT"
HEALTH="\$URL/_stcore/health"
PIDFILE="\$INSTALL_DIR/server.pid"
LOGFILE="\$INSTALL_DIR/server.log"

open_browser() {
    if command -v xdg-open >/dev/null 2>&1; then
        xdg-open "\$URL" >/dev/null 2>&1 &
    elif command -v gio >/dev/null 2>&1; then
        gio open "\$URL" >/dev/null 2>&1 &
    elif command -v open >/dev/null 2>&1; then
        open "\$URL" >/dev/null 2>&1 &
    else
        echo "Open \$URL in your browser."
    fi
}

server_alive() {
    # Streamlit's health endpoint responds with "ok" once the app is ready.
    curl -fsS --max-time 1 "\$HEALTH" >/dev/null 2>&1
}

# If a server is already up on \$PORT, just point the browser at it.
if server_alive; then
    echo "iidm-viewer is already running on \$URL — opening browser."
    open_browser
    exit 0
fi

echo "Starting iidm-viewer on \$URL ..."
# Notes:
# - The iidm-viewer CLI shells out to \`streamlit\` by name, so the
#   venv's bin/ must be on PATH (a \`.desktop\` launch inherits a
#   minimal PATH without it).
# - \`setsid\` puts the wrapper *and* its streamlit child into a fresh
#   process group, so \`kill -- -\$PID\` cleanly tears down the whole
#   tree later. Without it, killing the recorded PID would orphan the
#   real server.
PATH="\$VENV_DIR/bin:\$PATH" setsid nohup "\$VENV_DIR/bin/iidm-viewer" \\
    --server.headless=true \\
    --server.port=\$PORT \\
    --browser.gatherUsageStats=false \\
    >"\$LOGFILE" 2>&1 < /dev/null &
echo \$! > "\$PIDFILE"

# Wait up to ~30s for the server to come up.
for _ in \$(seq 1 60); do
    if server_alive; then
        open_browser
        exit 0
    fi
    sleep 0.5
done

echo "iidm-viewer failed to start within 30s. See \$LOGFILE for details." >&2
exit 1
EOF
chmod +x "$LAUNCHER"

# -----------------------------------------------------------------------------
# 4. Bash alias (idempotent)
# -----------------------------------------------------------------------------
RC_FILE="$HOME/.bashrc"
ALIAS_LINE="alias iidm-viewer='$LAUNCHER'"
MARKER="# iidm-viewer installer alias"
if [[ -f "$RC_FILE" ]] && grep -Fq "$MARKER" "$RC_FILE"; then
    log "Alias already present in $RC_FILE"
else
    {
        printf '\n%s\n' "$MARKER"
        printf '%s\n' "$ALIAS_LINE"
    } >> "$RC_FILE"
    log "Added 'iidm-viewer' alias to $RC_FILE"
fi

# -----------------------------------------------------------------------------
# 5. Icon (simple SVG, no external dependency)
# -----------------------------------------------------------------------------
log "Writing icon to $ICON_FILE"
cat > "$ICON_FILE" <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">
  <rect width="64" height="64" rx="10" fill="#0d4f8b"/>
  <g fill="none" stroke="#ffd83d" stroke-width="2.5" stroke-linecap="round">
    <line x1="16" y1="16" x2="32" y2="32"/>
    <line x1="48" y1="16" x2="32" y2="32"/>
    <line x1="16" y1="48" x2="32" y2="32"/>
    <line x1="48" y1="48" x2="32" y2="32"/>
    <line x1="32" y1="16" x2="32" y2="48"/>
  </g>
  <g fill="#ffd83d" stroke="#0d4f8b" stroke-width="1.5">
    <circle cx="16" cy="16" r="4"/>
    <circle cx="48" cy="16" r="4"/>
    <circle cx="16" cy="48" r="4"/>
    <circle cx="48" cy="48" r="4"/>
    <circle cx="32" cy="32" r="5"/>
  </g>
</svg>
EOF

# -----------------------------------------------------------------------------
# 6. Desktop entry
# -----------------------------------------------------------------------------
mkdir -p "$DESKTOP_DIR"
log "Writing desktop entry to $DESKTOP_FILE"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Type=Application
Version=1.0
Name=IIDM Viewer
GenericName=Power Network Viewer
Comment=Visualise and explore IIDM electrical network files
Exec=$LAUNCHER
Icon=$ICON_FILE
Terminal=false
Categories=Science;Engineering;Education;
Keywords=iidm;powsybl;power;grid;network;
StartupNotify=true
EOF
chmod +x "$DESKTOP_FILE"

if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "$DESKTOP_DIR" >/dev/null 2>&1 || true
fi

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------
cat <<EOF

iidm-viewer installation complete.

  Launch options:
    - Terminal:           open a new shell, then run:  iidm-viewer
                          (or, in the current shell:   source ~/.bashrc)
    - Applications menu:  search for "IIDM Viewer"
    - Direct:             $LAUNCHER

  The launcher reuses an existing server on port $PORT, so closing the
  browser tab and clicking the icon again will reopen the same session
  instead of spawning a duplicate process.

  To stop the running server (kills the whole process group):
      kill -- -\$(cat $INSTALL_DIR/server.pid)

  To uninstall:
      rm -rf $INSTALL_DIR $DESKTOP_FILE
      # then remove the alias block from ~/.bashrc

EOF
